// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: E:/Soft/Proje/LXCLUA/app/src/main/java/com/yan/luaeditor/tools/tokenizer/lua.flex

package com.yan.luaeditor.tools.tokenizer;

import static com.yan.luaeditor.tools.tokenizer.LuaTokenTypes.*;
import java.io.IOException;
import java.io.Reader;


@SuppressWarnings("fallthrough")
public class LuaLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int xSHEBANG = 2;
  public static final int xDOUBLE_QUOTED_STRING = 4;
  public static final int xSINGLE_QUOTED_STRING = 6;
  public static final int xBLOCK_STRING = 8;
  public static final int xBLOCK_COMMENT = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\10\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\2\36\1\40\1\36\11\41\1\42"+
    "\7\41\1\43\2\41\1\44\1\45\1\46\1\47\1\50"+
    "\1\0\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\41\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\41\1\70\1\71\1\72\1\73\1\74\1\75"+
    "\1\76\1\77\1\41\1\100\1\101\1\102\1\103\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\2\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\23\31\1\35\1\36"+
    "\1\37\1\40\1\41\2\42\1\41\2\43\1\44\1\0"+
    "\1\41\2\43\1\0\3\45\1\0\1\46\1\0\1\47"+
    "\1\50\1\51\2\0\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\21\4\0\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\1\73\1\74"+
    "\1\75\1\0\1\76\1\77\11\31\1\100\11\31\1\101"+
    "\1\31\1\102\1\103\10\31\1\104\14\31\1\105\1\106"+
    "\1\0\1\107\2\0\1\41\2\0\1\41\1\0\1\110"+
    "\1\0\1\111\1\55\1\112\3\55\1\113\1\114\1\115"+
    "\1\21\1\0\2\21\1\116\1\117\1\120\2\31\1\121"+
    "\1\122\10\31\1\123\4\31\1\124\7\31\1\125\1\126"+
    "\16\31\1\127\4\31\1\130\1\131\2\55\1\21\3\31"+
    "\1\132\7\31\1\133\1\134\5\31\1\135\5\31\1\136"+
    "\11\31\1\137\1\140\1\141\1\31\1\142\1\31\1\143"+
    "\2\55\3\0\1\31\1\144\1\145\1\146\1\31\1\147"+
    "\2\31\1\150\2\31\1\151\1\152\5\31\1\153\12\31"+
    "\1\154\1\155\2\55\1\156\1\157\4\31\1\160\3\31"+
    "\1\161\2\31\1\162\2\31\1\163\2\31\1\164\1\165"+
    "\1\166\1\167\1\170\2\55\1\31\1\171\1\31\1\172"+
    "\1\173\1\174\2\31\1\175\2\31\1\176\1\31\1\55"+
    "\1\177\1\200\1\201\1\202\2\31\1\203\1\31\1\55"+
    "\2\31\1\204\1\55\1\205\1\206\1\207";

  private static int [] zzUnpackAction() {
    int [] result = new int[369];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\u0154\0\u0198\0\u01dc"+
    "\0\u0198\0\u0220\0\u0264\0\u02a8\0\u02ec\0\u0330\0\u0374\0\u0198"+
    "\0\u0198\0\u03b8\0\u03fc\0\u0198\0\u0440\0\u0484\0\u04c8\0\u050c"+
    "\0\u0550\0\u0594\0\u0198\0\u05d8\0\u061c\0\u0660\0\u06a4\0\u0198"+
    "\0\u06e8\0\u072c\0\u0198\0\u0770\0\u07b4\0\u07f8\0\u083c\0\u0880"+
    "\0\u08c4\0\u0908\0\u094c\0\u0990\0\u09d4\0\u0a18\0\u0a5c\0\u0aa0"+
    "\0\u0ae4\0\u0b28\0\u0b6c\0\u0bb0\0\u0bf4\0\u0c38\0\u0c7c\0\u0198"+
    "\0\u0cc0\0\u0198\0\u0d04\0\u0d48\0\u0198\0\u0d8c\0\u0dd0\0\u0e14"+
    "\0\u0e58\0\u0198\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68\0\u0fac\0\u0ff0"+
    "\0\u1034\0\u1078\0\u0264\0\u0198\0\u10bc\0\u0198\0\u0198\0\u0198"+
    "\0\u0374\0\u1100\0\u0198\0\u0198\0\u0198\0\u1144\0\u0198\0\u0198"+
    "\0\u1188\0\u11cc\0\u0198\0\u1210\0\u1254\0\u1298\0\u12dc\0\u1320"+
    "\0\u0198\0\u0198\0\u1364\0\u13a8\0\u0198\0\u0198\0\u0198\0\u0198"+
    "\0\u13ec\0\u0198\0\u0198\0\u072c\0\u0198\0\u0198\0\u1430\0\u1474"+
    "\0\u14b8\0\u14fc\0\u1540\0\u1584\0\u15c8\0\u160c\0\u1650\0\u06e8"+
    "\0\u1694\0\u16d8\0\u171c\0\u1760\0\u17a4\0\u17e8\0\u182c\0\u1870"+
    "\0\u18b4\0\u06e8\0\u18f8\0\u06e8\0\u06e8\0\u193c\0\u1980\0\u19c4"+
    "\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18\0\u06e8\0\u1b5c\0\u1ba0"+
    "\0\u1be4\0\u1c28\0\u1c6c\0\u1cb0\0\u1cf4\0\u1d38\0\u1d7c\0\u1dc0"+
    "\0\u1e04\0\u1e48\0\u0198\0\u0198\0\u1e8c\0\u0198\0\u0e14\0\u1ed0"+
    "\0\u0e14\0\u0f24\0\u1f14\0\u0f24\0\u1034\0\u0198\0\u1078\0\u0198"+
    "\0\u1f58\0\u1f9c\0\u1fe0\0\u2024\0\u2068\0\u0198\0\u0198\0\u0198"+
    "\0\u20ac\0\u20f0\0\u2134\0\u2178\0\u0198\0\u0198\0\u0198\0\u21bc"+
    "\0\u2200\0\u06e8\0\u06e8\0\u2244\0\u2288\0\u22cc\0\u2310\0\u2354"+
    "\0\u2398\0\u23dc\0\u2420\0\u06e8\0\u2464\0\u24a8\0\u24ec\0\u2530"+
    "\0\u06e8\0\u2574\0\u25b8\0\u25fc\0\u2640\0\u2684\0\u26c8\0\u270c"+
    "\0\u06e8\0\u06e8\0\u2750\0\u2794\0\u27d8\0\u281c\0\u2860\0\u28a4"+
    "\0\u28e8\0\u292c\0\u2970\0\u29b4\0\u29f8\0\u2a3c\0\u2a80\0\u2ac4"+
    "\0\u06e8\0\u2b08\0\u2b4c\0\u2b90\0\u2bd4\0\u0198\0\u1f58\0\u2c18"+
    "\0\u2c5c\0\u2ca0\0\u2ce4\0\u2d28\0\u2d6c\0\u06e8\0\u2db0\0\u2df4"+
    "\0\u2e38\0\u2e7c\0\u2ec0\0\u2f04\0\u2f48\0\u2f8c\0\u06e8\0\u2fd0"+
    "\0\u3014\0\u3058\0\u309c\0\u30e0\0\u06e8\0\u3124\0\u3168\0\u31ac"+
    "\0\u31f0\0\u3234\0\u06e8\0\u3278\0\u32bc\0\u3300\0\u3344\0\u3388"+
    "\0\u33cc\0\u3410\0\u3454\0\u3498\0\u06e8\0\u06e8\0\u06e8\0\u34dc"+
    "\0\u06e8\0\u3520\0\u06e8\0\u3564\0\u35a8\0\u35ec\0\u3630\0\u3674"+
    "\0\u36b8\0\u06e8\0\u06e8\0\u06e8\0\u36fc\0\u06e8\0\u3740\0\u3784"+
    "\0\u06e8\0\u37c8\0\u380c\0\u06e8\0\u3850\0\u3894\0\u38d8\0\u391c"+
    "\0\u3960\0\u39a4\0\u06e8\0\u39e8\0\u3a2c\0\u3a70\0\u3ab4\0\u3af8"+
    "\0\u3b3c\0\u3b80\0\u3bc4\0\u3c08\0\u3c4c\0\u06e8\0\u06e8\0\u3c90"+
    "\0\u3cd4\0\u0198\0\u0198\0\u3d18\0\u3d5c\0\u3da0\0\u3de4\0\u06e8"+
    "\0\u3e28\0\u3e6c\0\u3eb0\0\u06e8\0\u3ef4\0\u3f38\0\u06e8\0\u3f7c"+
    "\0\u3fc0\0\u06e8\0\u4004\0\u4048\0\u06e8\0\u06e8\0\u06e8\0\u06e8"+
    "\0\u06e8\0\u408c\0\u40d0\0\u4114\0\u06e8\0\u4158\0\u06e8\0\u06e8"+
    "\0\u06e8\0\u419c\0\u41e0\0\u06e8\0\u4224\0\u4268\0\u06e8\0\u42ac"+
    "\0\u42f0\0\u4334\0\u06e8\0\u06e8\0\u06e8\0\u4378\0\u43bc\0\u06e8"+
    "\0\u4400\0\u4444\0\u4488\0\u44cc\0\u06e8\0\u4510\0\u06e8\0\u06e8"+
    "\0\u4554";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[369];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\0\1\10\1\12\1\7\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\2\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\6\41\1\42\1\7"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\41\1\55\1\56\1\57\1\41\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\41\1\67"+
    "\2\41\1\70\1\71\1\72\1\73\2\74\1\75\2\74"+
    "\1\76\76\74\2\77\1\100\2\77\1\101\1\77\1\102"+
    "\35\77\1\103\36\77\2\104\1\105\2\104\1\106\5\104"+
    "\1\102\31\104\1\107\36\104\46\110\1\111\103\110\1\112"+
    "\35\110\105\0\1\10\2\0\1\10\101\0\1\11\101\0"+
    "\7\113\1\114\35\113\1\115\36\113\6\0\1\116\127\0"+
    "\1\117\103\0\1\120\51\0\13\121\1\114\31\121\1\122"+
    "\36\121\32\0\1\123\70\0\1\124\12\0\1\125\72\0"+
    "\1\126\10\0\1\127\1\130\72\0\1\131\104\0\1\132"+
    "\6\0\1\133\73\0\1\134\1\0\3\31\10\0\1\135"+
    "\1\136\2\0\1\137\4\0\1\140\1\0\1\135\2\0"+
    "\1\136\20\0\1\137\27\0\1\134\1\0\3\31\11\0"+
    "\1\136\7\0\1\140\4\0\1\136\55\0\1\141\2\0"+
    "\1\142\102\0\1\143\1\144\46\0\1\145\34\0\1\146"+
    "\1\147\102\0\1\150\1\151\72\0\1\152\11\0\1\153"+
    "\73\0\3\41\7\0\6\41\4\0\30\41\36\0\1\154"+
    "\11\0\1\155\71\0\1\156\75\0\3\41\7\0\6\41"+
    "\4\0\20\41\1\157\7\41\30\0\3\41\7\0\6\41"+
    "\4\0\2\41\1\160\12\41\1\161\3\41\1\162\6\41"+
    "\30\0\3\41\7\0\6\41\4\0\20\41\1\163\7\41"+
    "\30\0\3\41\7\0\6\41\4\0\1\41\1\164\11\41"+
    "\1\165\2\41\1\166\11\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\167\10\41\1\170\11\41\30\0\3\41"+
    "\7\0\6\41\4\0\13\41\1\171\1\41\1\172\10\41"+
    "\1\173\1\41\30\0\3\41\7\0\6\41\4\0\1\41"+
    "\1\174\7\41\1\175\4\41\1\176\4\41\1\177\4\41"+
    "\30\0\3\41\7\0\6\41\4\0\13\41\1\200\2\41"+
    "\1\201\11\41\30\0\3\41\7\0\6\41\4\0\6\41"+
    "\1\202\5\41\1\203\1\204\3\41\1\205\6\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\206\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\207\14\41\1\210"+
    "\11\41\30\0\3\41\7\0\6\41\4\0\11\41\1\211"+
    "\4\41\1\212\11\41\30\0\3\41\7\0\6\41\4\0"+
    "\11\41\1\213\3\41\1\214\1\41\1\215\1\216\1\217"+
    "\6\41\30\0\3\41\7\0\6\41\4\0\20\41\1\220"+
    "\2\41\1\221\4\41\30\0\3\41\7\0\6\41\4\0"+
    "\5\41\1\222\22\41\30\0\3\41\7\0\6\41\4\0"+
    "\22\41\1\223\2\41\1\224\2\41\30\0\3\41\7\0"+
    "\6\41\4\0\1\41\1\225\6\41\1\226\7\41\1\227"+
    "\7\41\30\0\3\41\7\0\6\41\4\0\15\41\1\230"+
    "\12\41\30\0\3\41\7\0\6\41\4\0\10\41\1\231"+
    "\1\232\16\41\36\0\1\233\1\234\1\235\101\0\1\236"+
    "\51\0\2\74\1\0\2\74\1\0\76\74\2\0\1\75"+
    "\101\0\2\77\1\237\2\77\1\237\1\77\1\102\35\77"+
    "\1\240\36\77\7\237\1\102\35\237\1\240\40\237\1\100"+
    "\4\237\1\102\35\237\1\240\36\237\2\241\4\237\76\241"+
    "\2\104\1\242\2\104\1\242\5\104\1\102\31\104\1\243"+
    "\36\104\13\242\1\102\31\242\1\243\40\242\1\105\10\242"+
    "\1\102\31\242\1\243\36\242\2\244\4\242\76\244\46\110"+
    "\1\0\35\110\32\0\1\245\13\0\1\246\67\0\1\247"+
    "\13\0\1\250\35\0\104\113\104\121\2\251\1\0\2\251"+
    "\1\0\13\251\1\252\22\251\1\253\10\251\1\254\12\251"+
    "\1\255\13\251\22\0\1\256\7\0\1\257\103\0\1\260"+
    "\75\0\3\134\11\0\1\136\14\0\1\136\52\0\2\261"+
    "\75\0\1\262\1\0\1\262\2\0\3\263\101\0\3\264"+
    "\7\0\3\264\10\0\6\264\51\0\3\31\107\0\1\265"+
    "\104\0\1\266\102\0\1\267\75\0\3\41\7\0\6\41"+
    "\4\0\1\41\1\270\26\41\30\0\3\41\7\0\6\41"+
    "\4\0\21\41\1\271\6\41\30\0\3\41\7\0\6\41"+
    "\4\0\4\41\1\272\23\41\30\0\3\41\7\0\6\41"+
    "\4\0\14\41\1\273\13\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\274\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\21\41\1\275\1\276\5\41\30\0\3\41\7\0"+
    "\6\41\4\0\1\41\1\277\26\41\30\0\3\41\7\0"+
    "\6\41\4\0\14\41\1\300\1\301\12\41\30\0\3\41"+
    "\7\0\6\41\4\0\6\41\1\302\21\41\30\0\3\41"+
    "\7\0\6\41\4\0\21\41\1\303\6\41\30\0\3\41"+
    "\7\0\6\41\4\0\4\41\1\304\16\41\1\305\4\41"+
    "\30\0\3\41\7\0\6\41\4\0\22\41\1\306\5\41"+
    "\30\0\3\41\7\0\6\41\4\0\13\41\1\307\14\41"+
    "\30\0\3\41\7\0\6\41\4\0\15\41\1\310\12\41"+
    "\30\0\3\41\7\0\6\41\4\0\20\41\1\311\7\41"+
    "\30\0\3\41\7\0\6\41\4\0\15\41\1\312\12\41"+
    "\30\0\3\41\7\0\6\41\4\0\16\41\1\313\11\41"+
    "\30\0\3\41\7\0\6\41\4\0\22\41\1\314\5\41"+
    "\30\0\3\41\7\0\6\41\4\0\17\41\1\315\10\41"+
    "\30\0\3\41\7\0\6\41\4\0\27\41\1\316\30\0"+
    "\3\41\7\0\6\41\4\0\14\41\1\317\13\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\320\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\321\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\322\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\15\41\1\323\12\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\324\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\325\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\23\41\1\326\4\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\327\4\41\1\330"+
    "\11\41\30\0\3\41\7\0\6\41\4\0\2\41\1\331"+
    "\25\41\30\0\3\41\7\0\6\41\4\0\17\41\1\332"+
    "\2\41\1\333\5\41\30\0\3\41\7\0\6\41\4\0"+
    "\1\41\1\334\26\41\30\0\3\41\7\0\6\41\4\0"+
    "\11\41\1\335\16\41\30\0\3\41\7\0\6\41\4\0"+
    "\12\41\1\336\15\41\30\0\3\41\7\0\6\41\4\0"+
    "\5\41\1\337\22\41\30\0\3\41\7\0\6\41\4\0"+
    "\23\41\1\340\3\41\1\341\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\342\5\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\343\3\41\1\344\16\41\30\0\3\41"+
    "\7\0\6\41\4\0\22\41\1\345\5\41\37\0\1\346"+
    "\50\0\104\237\104\242\2\251\1\0\2\251\1\0\76\251"+
    "\2\252\1\0\2\252\1\0\76\252\2\251\1\0\2\251"+
    "\1\0\24\251\1\253\11\251\1\347\41\251\1\0\2\251"+
    "\1\0\57\251\1\350\20\251\1\0\2\251\1\0\47\251"+
    "\1\351\26\251\24\0\2\261\22\0\1\135\57\0\3\263"+
    "\101\0\3\263\21\0\1\262\55\0\1\352\1\0\3\264"+
    "\7\0\3\264\1\0\1\136\5\0\1\137\6\264\10\0"+
    "\1\136\40\0\3\41\7\0\6\41\4\0\25\41\1\353"+
    "\2\41\30\0\3\41\7\0\6\41\4\0\22\41\1\354"+
    "\5\41\30\0\3\41\7\0\6\41\4\0\1\41\1\355"+
    "\26\41\30\0\3\41\7\0\6\41\4\0\5\41\1\356"+
    "\22\41\30\0\3\41\7\0\6\41\4\0\3\41\1\357"+
    "\24\41\30\0\3\41\7\0\6\41\4\0\21\41\1\360"+
    "\6\41\30\0\3\41\7\0\6\41\4\0\14\41\1\361"+
    "\13\41\30\0\3\41\7\0\6\41\4\0\21\41\1\362"+
    "\1\363\5\41\30\0\3\41\7\0\6\41\4\0\1\41"+
    "\1\364\3\41\1\365\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\366\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\14\41\1\367\13\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\370\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\21\41\1\371\6\41\30\0\3\41\7\0\6\41"+
    "\4\0\1\41\1\372\26\41\30\0\3\41\7\0\6\41"+
    "\4\0\3\41\1\373\24\41\30\0\3\41\7\0\6\41"+
    "\4\0\2\41\1\374\25\41\30\0\3\41\7\0\6\41"+
    "\4\0\16\41\1\375\11\41\30\0\3\41\7\0\6\41"+
    "\4\0\13\41\1\376\14\41\30\0\3\41\7\0\6\41"+
    "\4\0\25\41\1\377\2\41\30\0\3\41\7\0\6\41"+
    "\4\0\2\41\1\u0100\25\41\30\0\3\41\7\0\6\41"+
    "\4\0\1\41\1\u0101\26\41\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\u0102\5\41\30\0\3\41\7\0\6\41"+
    "\4\0\25\41\1\u0103\2\41\30\0\3\41\7\0\6\41"+
    "\4\0\20\41\1\u0104\7\41\30\0\3\41\7\0\6\41"+
    "\4\0\17\41\1\u0105\10\41\30\0\3\41\7\0\6\41"+
    "\4\0\24\41\1\u0106\3\41\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\u0107\5\41\30\0\3\41\7\0\6\41"+
    "\4\0\13\41\1\u0108\14\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\u0109\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\23\41\1\u010a\4\41\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\u010b\5\41\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\u010c\5\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\u010d\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\15\41\1\u010e\12\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\u010f\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\11\41\1\u0110\16\41\30\0\3\41\7\0\6\41"+
    "\4\0\15\41\1\u0111\12\41\30\0\3\41\7\0\6\41"+
    "\4\0\13\41\1\u0112\14\41\30\0\3\41\7\0\6\41"+
    "\4\0\10\41\1\u0113\17\41\4\0\2\251\1\0\2\251"+
    "\1\0\46\251\1\u0114\31\251\1\0\2\251\1\0\51\251"+
    "\1\u0115\24\251\24\0\3\352\7\0\3\352\1\0\1\136"+
    "\6\0\6\352\10\0\1\136\23\0\1\u0116\3\0\1\u0117"+
    "\10\0\3\41\7\0\6\41\1\u0118\3\0\30\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u0119\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\12\41\1\u011a\15\41\30\0"+
    "\3\41\7\0\6\41\4\0\10\41\1\u011b\17\41\30\0"+
    "\3\41\7\0\6\41\4\0\21\41\1\u011c\6\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u011d\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u011e\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\u011f\16\41\30\0"+
    "\3\41\7\0\6\41\4\0\23\41\1\u0120\4\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u0121\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\u0122\16\41\30\0"+
    "\3\41\7\0\6\41\4\0\15\41\1\u0123\12\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u0124\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u0125\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u0126\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u0127\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u0128\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\16\41\1\u0129\11\41\30\0"+
    "\3\41\7\0\6\41\4\0\4\41\1\u012a\23\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u012b\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u012c\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u012d\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u012e\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u012f\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u0130\22\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\u0131\16\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u0132\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u0133\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\u0134\16\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\u0135\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u0136\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u0137\22\41\4\0"+
    "\2\251\1\0\2\251\1\0\62\251\1\u0138\15\251\1\0"+
    "\2\251\1\0\53\251\1\u0139\22\251\7\u0116\1\u013a\74\u0116"+
    "\13\u0117\1\u013a\70\u0117\32\0\1\u0118\11\0\1\u013b\63\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u013c\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\15\41\1\u013d\12\41\30\0"+
    "\3\41\7\0\6\41\4\0\15\41\1\u013e\12\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u013f\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\6\41\1\u0140\21\41\30\0"+
    "\3\41\7\0\6\41\4\0\4\41\1\u0141\23\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u0142\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\11\41\1\u0143\16\41\30\0"+
    "\3\41\7\0\6\41\4\0\13\41\1\u0144\14\41\30\0"+
    "\3\41\7\0\6\41\4\0\14\41\1\u0145\13\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u0146\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\1\41\1\u0147\26\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u0148\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u0149\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\20\41\1\u014a\7\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u014b\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\u014c\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\u014d\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u014e\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\15\41\1\u014f\12\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\u0150\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\10\41\1\u0151\17\41\4\0"+
    "\2\251\1\0\2\251\1\0\47\251\1\u0152\30\251\1\0"+
    "\2\251\1\0\60\251\1\u0153\15\251\24\0\3\41\7\0"+
    "\6\41\4\0\3\41\1\u0154\24\41\30\0\3\41\7\0"+
    "\6\41\4\0\4\41\1\u0155\23\41\30\0\3\41\7\0"+
    "\6\41\4\0\23\41\1\u0156\4\41\30\0\3\41\7\0"+
    "\6\41\4\0\22\41\1\u0157\5\41\30\0\3\41\7\0"+
    "\6\41\4\0\21\41\1\u0158\6\41\30\0\3\41\7\0"+
    "\6\41\4\0\27\41\1\u0159\30\0\3\41\7\0\6\41"+
    "\4\0\16\41\1\u015a\11\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\u015b\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\4\41\1\u015c\23\41\30\0\3\41\7\0\6\41"+
    "\4\0\6\41\1\u015d\21\41\30\0\3\41\7\0\6\41"+
    "\4\0\16\41\1\u015e\11\41\30\0\3\41\7\0\6\41"+
    "\4\0\5\41\1\u015f\22\41\30\0\3\41\7\0\6\41"+
    "\4\0\22\41\1\u0160\5\41\4\0\2\251\1\0\2\251"+
    "\1\0\51\251\1\u0161\26\251\1\0\2\251\1\0\57\251"+
    "\1\u0162\16\251\24\0\3\41\7\0\6\41\4\0\22\41"+
    "\1\u0163\5\41\30\0\3\41\7\0\6\41\4\0\5\41"+
    "\1\u0164\22\41\30\0\3\41\7\0\6\41\4\0\15\41"+
    "\1\u0165\12\41\30\0\3\41\7\0\6\41\4\0\15\41"+
    "\1\u0166\12\41\30\0\3\41\7\0\6\41\4\0\1\41"+
    "\1\u0167\26\41\30\0\3\41\7\0\6\41\4\0\20\41"+
    "\1\u0168\7\41\30\0\3\41\7\0\6\41\4\0\5\41"+
    "\1\u0169\22\41\4\0\2\251\1\0\2\251\1\0\53\251"+
    "\1\u016a\22\251\2\u0162\1\0\2\u0162\1\0\76\u0162\24\0"+
    "\3\41\7\0\6\41\4\0\22\41\1\u016b\5\41\30\0"+
    "\3\41\7\0\6\41\4\0\3\41\1\u016c\24\41\30\0"+
    "\3\41\7\0\6\41\4\0\4\41\1\u016d\23\41\4\0"+
    "\2\251\1\0\2\251\1\0\60\251\1\u016e\15\251\24\0"+
    "\3\41\7\0\6\41\4\0\21\41\1\u016f\6\41\30\0"+
    "\3\41\7\0\6\41\4\0\5\41\1\u0170\22\41\4\0"+
    "\2\251\1\0\2\251\1\0\57\251\1\u0171\16\251\2\u0171"+
    "\1\0\2\u0171\1\0\76\u0171";

  private static int [] zzUnpacktrans() {
    int [] result = new int[17816];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\1\1\1\11\6\1\2\11\2\1\1\11"+
    "\6\1\1\11\4\1\1\11\2\1\1\11\24\1\1\11"+
    "\1\1\1\11\2\1\1\11\4\1\1\11\1\0\3\1"+
    "\1\0\3\1\1\0\1\11\1\0\3\11\2\0\3\11"+
    "\1\1\2\11\2\1\1\11\1\1\4\0\2\11\2\1"+
    "\4\11\1\1\2\11\1\0\2\11\54\1\2\11\1\0"+
    "\1\11\2\0\1\1\2\0\1\1\1\0\1\11\1\0"+
    "\1\11\5\1\3\11\1\1\1\0\2\1\3\11\56\1"+
    "\1\11\57\1\3\0\41\1\2\11\66\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[369];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

  /**
   * CharSequence 适配器，用于从 CharSequence 读取字符
   */
  static class CharSeqReader extends Reader
  {
    int offset = 0;
    CharSequence src;

    CharSeqReader(CharSequence src)
    {
      this.src = src;
    }

    @Override
    public void close() throws IOException
    {
      src = null;
      offset = 0;
    }

    @Override
    public int read(char[] chars, int i, int i1) throws IOException
    {
      int len = Math.min(src.length() - offset, i1);
      for (int n = 0; n < len; n++)
      {
        try{
          char c = src.charAt(offset++);
          chars[i++] = c;
        }catch(Exception e){
          // ignore
        }
      }
      if (len <= 0)
        return -1;
      return len;
    }
  }

  /**
   * 从 CharSequence 创建词法分析器
   */
  public LuaLexer(CharSequence src) {
    this(new CharSeqReader(src));
  }

  /**
   * 获取当前行号
   */
  public int yyline(){
    return yyline;
  }
  
  /**
   * 获取当前列号
   */
  public int yycolumn(){
    return yycolumn;
  }
  
  /**
   * 获取当前字符位置
   */
  public int yychar(){
    return (int)yychar;
  }
  
  // 块字符串/注释的等号数量
  private int nBrackets = 0;
  // 块内容缓冲区
  private StringBuilder blockBuffer = new StringBuilder();
  // 块开始标记
  private String blockStart = "";
  // 用于存储完整的块内容（开始标记 + 内容 + 结束标记）
  private String fullBlockContent = "";
  
  /**
   * 检查指定偏移处是否为指定字符
   */
  private boolean checkAhead(char c, int offset) {
    int pos = this.zzMarkedPos + offset;
    return pos < this.zzBuffer.length && this.zzBuffer[pos] == c;
  }

  /**
   * 检查并解析块字符串/注释的开始标记 [=*[
   * 设置 nBrackets 为等号数量
   * @return 是否是有效的块开始标记
   */
  private boolean checkBlock() {
    nBrackets = 0;
    if (checkAhead('[', 0)) {
      int n = 0;
      while (checkAhead('=', n + 1)) n++;
      if (checkAhead('[', n + 1)) {
        nBrackets = n;
        return true;
      }
    }
    return false;
  }

  /**
   * 从当前匹配文本中解析块开始标记的等号数量
   * 用于 [[, [=[, [==[, 等形式
   */
  private void parseBlockBrackets() {
    String text = yytext();
    nBrackets = 0;
    for (int i = 1; i < text.length() - 1; i++) {
      if (text.charAt(i) == '=') nBrackets++;
    }
  }

  /**
   * 检查块字符串/注释是否已闭合
   * @return 闭合标记后多余的字符数，-1 表示未闭合
   */
  private int checkBlockEnd() {
    String cs = blockBuffer.toString();
    StringBuilder closer = new StringBuilder("]");
    for (int i = 0; i < nBrackets; i++) closer.append('=');
    closer.append(']');
    int index = cs.indexOf(closer.toString());
    if (index >= 0) {
      return cs.length() - index - nBrackets - 2;
    }
    return -1;
  }

  /**
   * 获取完整的块内容（长字符串或块注释）
   * 包含开始标记、内容和结束标记
   * @return 完整的块内容
   */
  public String getBlockContent() {
    return fullBlockContent;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LuaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LuaTokenTypes advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case xSHEBANG: {
              yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }  // fall though
            case 370: break;
            case xDOUBLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 371: break;
            case xSINGLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 372: break;
            case xBLOCK_STRING: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BAD_CHARACTER;
            }  // fall though
            case 373: break;
            case xBLOCK_COMMENT: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BLOCK_COMMENT;
            }  // fall though
            case 374: break;
            default:
              {
                return null;
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 136: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 137: break;
          case 3:
            { return NEW_LINE;
            }
          // fall through
          case 138: break;
          case 4:
            { yybegin(xDOUBLE_QUOTED_STRING);
            }
          // fall through
          case 139: break;
          case 5:
            { return GETN;
            }
          // fall through
          case 140: break;
          case 6:
            { return MOD;
            }
          // fall through
          case 141: break;
          case 7:
            { return BIT_AND;
            }
          // fall through
          case 142: break;
          case 8:
            { yybegin(xSINGLE_QUOTED_STRING);
            }
          // fall through
          case 143: break;
          case 9:
            { return LPAREN;
            }
          // fall through
          case 144: break;
          case 10:
            { return RPAREN;
            }
          // fall through
          case 145: break;
          case 11:
            { return MULT;
            }
          // fall through
          case 146: break;
          case 12:
            { return PLUS;
            }
          // fall through
          case 147: break;
          case 13:
            { return COMMA;
            }
          // fall through
          case 148: break;
          case 14:
            { return MINUS;
            }
          // fall through
          case 149: break;
          case 15:
            { return DOT;
            }
          // fall through
          case 150: break;
          case 16:
            { return DIV;
            }
          // fall through
          case 151: break;
          case 17:
            { return NUMBER;
            }
          // fall through
          case 152: break;
          case 18:
            { return COLON;
            }
          // fall through
          case 153: break;
          case 19:
            { return SEMI;
            }
          // fall through
          case 154: break;
          case 20:
            { return LT;
            }
          // fall through
          case 155: break;
          case 21:
            { return ASSIGN;
            }
          // fall through
          case 156: break;
          case 22:
            { return GT;
            }
          // fall through
          case 157: break;
          case 23:
            { return QUESTION;
            }
          // fall through
          case 158: break;
          case 24:
            { return AT;
            }
          // fall through
          case 159: break;
          case 25:
            { return NAME;
            }
          // fall through
          case 160: break;
          case 26:
            { return LBRACK;
            }
          // fall through
          case 161: break;
          case 27:
            { return RBRACK;
            }
          // fall through
          case 162: break;
          case 28:
            { return EXP;
            }
          // fall through
          case 163: break;
          case 29:
            { return LCURLY;
            }
          // fall through
          case 164: break;
          case 30:
            { return BIT_OR;
            }
          // fall through
          case 165: break;
          case 31:
            { return RCURLY;
            }
          // fall through
          case 166: break;
          case 32:
            { return BIT_TILDE;
            }
          // fall through
          case 167: break;
          case 33:
            { 
            }
          // fall through
          case 168: break;
          case 34:
            { yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }
          // fall through
          case 169: break;
          case 35:
            { yybegin(YYINITIAL); return BAD_CHARACTER;
            }
          // fall through
          case 170: break;
          case 36:
            { yybegin(YYINITIAL); return STRING;
            }
          // fall through
          case 171: break;
          case 37:
            { blockBuffer.append(yytext());
            }
          // fall through
          case 172: break;
          case 38:
            { return STRING;
            }
          // fall through
          case 173: break;
          case 39:
            { yybegin(xSHEBANG); return SHEBANG;
            }
          // fall through
          case 174: break;
          case 40:
            { return MODEQ;
            }
          // fall through
          case 175: break;
          case 41:
            { return BANDEQ;
            }
          // fall through
          case 176: break;
          case 42:
            { return MULEQ;
            }
          // fall through
          case 177: break;
          case 43:
            { return PLUSPLUS;
            }
          // fall through
          case 178: break;
          case 44:
            { return ADDEQ;
            }
          // fall through
          case 179: break;
          case 45:
            { return SHORT_COMMENT;
            }
          // fall through
          case 180: break;
          case 46:
            { return SUBEQ;
            }
          // fall through
          case 181: break;
          case 47:
            { return LEF;
            }
          // fall through
          case 182: break;
          case 48:
            { return CONCAT;
            }
          // fall through
          case 183: break;
          case 49:
            { return DOUBLE_DIV;
            }
          // fall through
          case 184: break;
          case 50:
            { return DIVEQ;
            }
          // fall through
          case 185: break;
          case 51:
            { return DOUBLE_COLON;
            }
          // fall through
          case 186: break;
          case 52:
            { return WALRUS;
            }
          // fall through
          case 187: break;
          case 53:
            { return BIT_LTLT;
            }
          // fall through
          case 188: break;
          case 54:
            { return LE;
            }
          // fall through
          case 189: break;
          case 55:
            { return REVPIPE;
            }
          // fall through
          case 190: break;
          case 56:
            { return EQ;
            }
          // fall through
          case 191: break;
          case 57:
            { return MEAN;
            }
          // fall through
          case 192: break;
          case 58:
            { return GE;
            }
          // fall through
          case 193: break;
          case 59:
            { return BIT_RTRT;
            }
          // fall through
          case 194: break;
          case 60:
            { return OPTCHAIN;
            }
          // fall through
          case 195: break;
          case 61:
            { return NULLCOAL;
            }
          // fall through
          case 196: break;
          case 62:
            { blockStart = yytext();
                              parseBlockBrackets();
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 197: break;
          case 63:
            { return BXOREQ;
            }
          // fall through
          case 198: break;
          case 64:
            { return DO;
            }
          // fall through
          case 199: break;
          case 65:
            { return IF;
            }
          // fall through
          case 200: break;
          case 66:
            { return IN;
            }
          // fall through
          case 201: break;
          case 67:
            { return IS;
            }
          // fall through
          case 202: break;
          case 68:
            { return OR;
            }
          // fall through
          case 203: break;
          case 69:
            { return BOREQ;
            }
          // fall through
          case 204: break;
          case 70:
            { return PIPE;
            }
          // fall through
          case 205: break;
          case 71:
            { return NE;
            }
          // fall through
          case 206: break;
          case 72:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return LONG_STRING;
                              }
            }
          // fall through
          case 207: break;
          case 73:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return BLOCK_COMMENT;
                              }
            }
          // fall through
          case 208: break;
          case 74:
            { return DOC_COMMENT;
            }
          // fall through
          case 209: break;
          case 75:
            { return ELLIPSIS;
            }
          // fall through
          case 210: break;
          case 76:
            { return CONCATEQ;
            }
          // fall through
          case 211: break;
          case 77:
            { return IDIVEQ;
            }
          // fall through
          case 212: break;
          case 78:
            { return SHLEQ;
            }
          // fall through
          case 213: break;
          case 79:
            { return SPACESHIP;
            }
          // fall through
          case 214: break;
          case 80:
            { return SHREQ;
            }
          // fall through
          case 215: break;
          case 81:
            { return AND;
            }
          // fall through
          case 216: break;
          case 82:
            { return ASM;
            }
          // fall through
          case 217: break;
          case 83:
            { return END;
            }
          // fall through
          case 218: break;
          case 84:
            { return FOR;
            }
          // fall through
          case 219: break;
          case 85:
            { return NIL;
            }
          // fall through
          case 220: break;
          case 86:
            { return NOT;
            }
          // fall through
          case 221: break;
          case 87:
            { return TRY;
            }
          // fall through
          case 222: break;
          case 88:
            { return SAFEPIPE;
            }
          // fall through
          case 223: break;
          case 89:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 3; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_COMMENT);
            }
          // fall through
          case 224: break;
          case 90:
            { return CASE;
            }
          // fall through
          case 225: break;
          case 91:
            { return ELSE;
            }
          // fall through
          case 226: break;
          case 92:
            { return ENUM;
            }
          // fall through
          case 227: break;
          case 93:
            { return GOTO;
            }
          // fall through
          case 228: break;
          case 94:
            { return NEW;
            }
          // fall through
          case 229: break;
          case 95:
            { return TAKE;
            }
          // fall through
          case 230: break;
          case 96:
            { return THEN;
            }
          // fall through
          case 231: break;
          case 97:
            { return TRUE;
            }
          // fall through
          case 232: break;
          case 98:
            { return WHEN;
            }
          // fall through
          case 233: break;
          case 99:
            { return WITH;
            }
          // fall through
          case 234: break;
          case 100:
            { return BREAK;
            }
          // fall through
          case 235: break;
          case 101:
            { return CATCH;
            }
          // fall through
          case 236: break;
          case 102:
            { return CLASS;
            }
          // fall through
          case 237: break;
          case 103:
            { return CONST;
            }
          // fall through
          case 238: break;
          case 104:
            { return DEFER;
            }
          // fall through
          case 239: break;
          case 105:
            { return FALSE;
            }
          // fall through
          case 240: break;
          case 106:
            { return FINAL;
            }
          // fall through
          case 241: break;
          case 107:
            { return LOCAL;
            }
          // fall through
          case 242: break;
          case 108:
            { return UNTIL;
            }
          // fall through
          case 243: break;
          case 109:
            { return WHILE;
            }
          // fall through
          case 244: break;
          case 110:
            { return RAW_STRING;
            }
          // fall through
          case 245: break;
          case 111:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 2; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 246: break;
          case 112:
            { return ELSEIF;
            }
          // fall through
          case 247: break;
          case 113:
            { return GLOBAL;
            }
          // fall through
          case 248: break;
          case 114:
            { return LAMBDA;
            }
          // fall through
          case 249: break;
          case 115:
            { return SUPER;
            }
          // fall through
          case 250: break;
          case 116:
            { return PUBLIC;
            }
          // fall through
          case 251: break;
          case 117:
            { return REPEAT;
            }
          // fall through
          case 252: break;
          case 118:
            { return RETURN;
            }
          // fall through
          case 253: break;
          case 119:
            { return STATIC;
            }
          // fall through
          case 254: break;
          case 120:
            { return SWITCH;
            }
          // fall through
          case 255: break;
          case 121:
            { return COMMAND;
            }
          // fall through
          case 256: break;
          case 122:
            { return DEFAULT;
            }
          // fall through
          case 257: break;
          case 123:
            { return EXTENDS;
            }
          // fall through
          case 258: break;
          case 124:
            { return FINALLY;
            }
          // fall through
          case 259: break;
          case 125:
            { return KEYWORD;
            }
          // fall through
          case 260: break;
          case 126:
            { return PRIVATE;
            }
          // fall through
          case 261: break;
          case 127:
            { return REGION;
            }
          // fall through
          case 262: break;
          case 128:
            { return ABSTRACT;
            }
          // fall through
          case 263: break;
          case 129:
            { return CONTINUE;
            }
          // fall through
          case 264: break;
          case 130:
            { return FUNCTION;
            }
          // fall through
          case 265: break;
          case 131:
            { return OPERATOR_KW;
            }
          // fall through
          case 266: break;
          case 132:
            { return PROTECTED;
            }
          // fall through
          case 267: break;
          case 133:
            { return IMPLEMENTS;
            }
          // fall through
          case 268: break;
          case 134:
            { return INTERFACE;
            }
          // fall through
          case 269: break;
          case 135:
            { return ENDREGION;
            }
          // fall through
          case 270: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
